default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["POSTGRESQL_USERNAME"] %>
  password: <%= ENV["POSTGRESQL_PASSWORD"] %>
  pool: 5
development:
  <<: *default
  database: apocrypha_development
test:
  <<: *default
  database: apocrypha_test
production:
  <<: *default
  database: apocrypha_production
  username: apocrypha
  password: <%= ENV['APOCRYPHA_DATABASE_PASSWORD'] %>
